export function buildCoreExports(typeScale, settings) {
  const json = JSON.stringify(
    typeScale.map((item) => ({
      name: item.label,
      technicalName: item.label,
      fontFamily: settings.fontFamily,
      fontSize: convertSize(item.fontSize, settings),
      fontWeight: getWeight(item),
      lineHeight: item.lineHeight,
      letterSpacing: item.letterSpacing,
    })),
    null,
    2,
  );

  const cssTokens = typeScale
    .map((item) => {
      const name = item.semanticName || item.id;
      const size =
        settings.fluidTypography && item.clampValue
          ? item.clampValue
          : formatSizeValue(item.fontSize, settings);
      return `  --${name}-size: ${size};
  --${name}-weight: ${getWeight(item)};
  --${name}-line-height: ${item.lineHeight};
  --${name}-letter-spacing: ${item.letterSpacing}em;`;
    })
    .join("\n\n");

  const css = `${settings.fluidTypography ? "/* Fluid Typography with CSS clamp() */\n" : ""}:root {
  /* Font Family */
  --font-family: ${settings.fontFamily};

  /* Type Scale */
${cssTokens}
}`;

  const scssTokens = typeScale
    .map((item) => {
      const name = item.semanticName || item.id;
      const size =
        settings.fluidTypography && item.clampValue
          ? item.clampValue
          : formatSizeValue(item.fontSize, settings);
      return `$${name}-size: ${size};
$${name}-weight: ${getWeight(item)};
$${name}-line-height: ${item.lineHeight};
$${name}-letter-spacing: ${item.letterSpacing}em;`;
    })
    .join("\n\n");

  const scss = `${settings.fluidTypography ? "// Fluid Typography with CSS clamp()\n" : ""}// Font Family
$font-family: ${settings.fontFamily};

// Type Scale
${scssTokens}`;

  return { json, css, scss };
}

export function buildPlatformExport(typeScale, settings, format, options) {
  if (format === "ios") return buildIosExport(typeScale, settings, options);
  if (format === "android")
    return buildAndroidExport(typeScale, settings, options);
  if (format === "flutter")
    return buildFlutterExport(typeScale, settings, options);
  if (format === "react-native")
    return buildReactNativeExport(typeScale, settings, options);
  if (format === "design-tokens")
    return buildDesignTokensExport(typeScale, settings, options);
  if (format === "figma")
    return buildFigmaPluginExport(typeScale, settings, options);
  if (format === "cli-config") return buildCliConfigExport(typeScale, settings);
  return "";
}

function formatSizeValue(value, settings) {
  return `${convertSize(value, settings)}${settings.unit}`;
}

function convertSize(value, settings) {
  if (settings.unit === "rem") return trim(value / settings.baseFontSize);
  if (settings.unit === "pt") return trim(value / 1.333);
  return trim(value);
}

function trim(value) {
  const rounded = Number(value.toFixed(2));
  return Number.isInteger(rounded) ? rounded : rounded;
}

function getWeight(item) {
  return item.weight ?? item.fontWeight;
}

function buildIosExport(typeScale, settings, options) {
  const header = options.includeComments
    ? `//\n// Typography Scale\n// Generated by Type Scale Tool\n// Base font size: ${settings.baseFontSize}px\n// Scale ratio: ${settings.scaleRatio}\n// Font family: ${settings.fontFamily}\n//\n\nimport UIKit\n\n`
    : "import UIKit\n\n";
  const fonts = typeScale
    .map((item) => {
      const name = platformTokenName(item, options);
      const size = Math.round(item.fontSize);
      const comment = options.includeComments
        ? `        // ${item.label} - ${size}pt\n`
        : "";

      return `${comment}        static let ${name} = UIFont.systemFont(ofSize: ${size}, weight: .${iosWeight(getWeight(item))})`;
    })
    .join("\n");
  const typography = `extension UIFont {\n    ${options.includeComments ? "// Typography Scale\n    " : ""}static let typography = Typography()\n    \n    struct Typography {\n${fonts}\n    }\n}`;

  if (!options.includeLineHeight && !options.includeLetterSpacing) {
    return header + typography;
  }

  const styles = typeScale
    .map((item) => {
      const name = platformTokenName(item, options);
      const size = Math.round(item.fontSize);
      const lineHeight = Math.round(size * item.lineHeight);
      const comment = options.includeComments
        ? `        // ${item.label}\n`
        : "";
      let style = `${comment}        static var ${name}: NSMutableParagraphStyle {\n            let style = NSMutableParagraphStyle()`;

      if (options.includeLineHeight) {
        style += `\n            style.minimumLineHeight = ${lineHeight}\n            style.maximumLineHeight = ${lineHeight}`;
      }

      return `${style}\n            return style\n        }`;
    })
    .join("\n");

  return `${header}${typography}\n\nextension NSMutableParagraphStyle {\n    ${options.includeComments ? "// Text Styles with Line Height and Letter Spacing\n    " : ""}static let textStyles = TextStyles()\n    \n    struct TextStyles {\n${styles}\n    }\n}`;
}

function buildAndroidExport(typeScale, settings, options) {
  const header = options.includeComments
    ? `/**\n * Typography Scale\n * Generated by Type Scale Tool\n * Base font size: ${settings.baseFontSize}px\n * Scale ratio: ${settings.scaleRatio}\n * Font family: ${settings.fontFamily}\n */\n\npackage com.yourapp.ui.theme\n\nimport androidx.compose.ui.text.TextStyle\nimport androidx.compose.ui.text.font.FontWeight\nimport androidx.compose.ui.unit.sp\n\n`
    : "package com.yourapp.ui.theme\n\nimport androidx.compose.ui.text.TextStyle\nimport androidx.compose.ui.text.font.FontWeight\nimport androidx.compose.ui.unit.sp\n\n";
  const tokens = typeScale
    .map((item) => {
      const name = platformTokenName(item, options);
      const size = Math.round(item.fontSize);
      const comment = options.includeComments
        ? `    // ${item.label} - ${size}sp\n`
        : "";
      let token = `${comment}    val ${name} = TextStyle(\n        fontSize = ${size}.sp`;

      if (options.includeFontWeight) {
        token += `,\n        fontWeight = FontWeight.${androidWeight(getWeight(item))}`;
      }
      if (options.includeLineHeight) {
        token += `,\n        lineHeight = ${(size * item.lineHeight).toFixed(1)}.sp`;
      }
      if (options.includeLetterSpacing && item.letterSpacing !== 0) {
        token += `,\n        letterSpacing = ${item.letterSpacing.toFixed(3)}.sp`;
      }

      return `${token}\n    )`;
    })
    .join("\n\n");

  return `${header}object Typography {\n${tokens}\n}`;
}

function buildFlutterExport(typeScale, settings, options) {
  const header = options.includeComments
    ? `///\n/// Typography Scale\n/// Generated by Type Scale Tool\n/// Base font size: ${settings.baseFontSize}px\n/// Scale ratio: ${settings.scaleRatio}\n/// Font family: ${settings.fontFamily}\n///\n\nimport 'package:flutter/material.dart';\n\n`
    : "import 'package:flutter/material.dart';\n\n";
  const tokens = typeScale
    .map((item) => {
      const name = platformTokenName(item, options);
      const size = Number(item.fontSize);
      const comment = options.includeComments
        ? `  /// ${item.label} - ${size.toFixed(1)}px\n`
        : "";
      let token = `${comment}  static const TextStyle ${name} = TextStyle(\n    fontSize: ${size.toFixed(1)}`;

      if (options.includeFontWeight) {
        token += `,\n    fontWeight: FontWeight.${flutterWeight(getWeight(item))}`;
      }
      if (options.includeLineHeight) {
        token += `,\n    height: ${item.lineHeight.toFixed(2)}`;
      }
      if (options.includeLetterSpacing && item.letterSpacing !== 0) {
        token += `,\n    letterSpacing: ${item.letterSpacing.toFixed(3)}`;
      }

      return `${token},\n  );`;
    })
    .join("\n\n");

  return `${header}class AppTypography {\n${tokens}\n}`;
}

function buildReactNativeExport(typeScale, settings, options) {
  const header = options.includeComments
    ? `/**\n * Typography Scale\n * Generated by Type Scale Tool\n * Base font size: ${settings.baseFontSize}px\n * Scale ratio: ${settings.scaleRatio}\n * Font family: ${settings.fontFamily}\n */\n\nimport { TextStyle } from 'react-native';\n\n`
    : "import { TextStyle } from 'react-native';\n\n";
  const tokens = typeScale
    .map((item) => {
      const name = platformTokenName(item, options);
      const size = Math.round(item.fontSize);
      const comment = options.includeComments
        ? `  // ${item.label} - ${size}px\n`
        : "";
      let token = `${comment}  ${name}: {\n    fontSize: ${size}`;

      if (options.includeFontWeight) {
        token += `,\n    fontWeight: '${reactNativeWeight(getWeight(item))}'`;
      }
      if (options.includeLineHeight) {
        token += `,\n    lineHeight: ${Math.round(size * item.lineHeight)}`;
      }
      if (options.includeLetterSpacing && item.letterSpacing !== 0) {
        token += `,\n    letterSpacing: ${item.letterSpacing.toFixed(3)}`;
      }

      return `${token},\n  } as TextStyle`;
    })
    .join(",\n\n");

  return `${header}export const typography = {\n${tokens}\n} as const;\n\nexport type TypographyKeys = keyof typeof typography;`;
}

function buildDesignTokensExport(typeScale, settings, options) {
  const tokens = {
    typography: {
      fontFamily: {
        primary: {
          value: settings.fontFamily,
          type: "fontFamily",
        },
      },
      fontSize: {},
      fontWeight: {},
      lineHeight: {},
      letterSpacing: {},
    },
  };

  typeScale.forEach((item) => {
    const name = platformTokenName(item, options);
    tokens.typography.fontSize[name] = {
      value:
        settings.fluidTypography && item.clampValue
          ? item.clampValue
          : `${item.fontSize}px`,
      type: "fontSize",
      description: item.label,
    };
    if (options.includeFontWeight) {
      tokens.typography.fontWeight[name] = {
        value: getWeight(item),
        type: "fontWeight",
      };
    }
    if (options.includeLineHeight) {
      tokens.typography.lineHeight[name] = {
        value: item.lineHeight,
        type: "lineHeight",
      };
    }
    if (options.includeLetterSpacing) {
      tokens.typography.letterSpacing[name] = {
        value: `${item.letterSpacing}em`,
        type: "letterSpacing",
      };
    }
  });

  return JSON.stringify(tokens, null, 2);
}

function buildFigmaPluginExport(typeScale, settings, options) {
  return JSON.stringify(
    {
      version: "1.0",
      typography: typeScale.map((item) => ({
        name:
          options.useSemanticNames && item.semanticName
            ? item.semanticName
            : item.id,
        fontFamily: settings.fontFamily
          .split(",")[0]
          .replace(/['"]/g, "")
          .trim(),
        fontSize: Math.round(item.fontSize),
        fontWeight: getWeight(item),
        lineHeight: options.includeLineHeight
          ? {
              value: Math.round(item.fontSize * item.lineHeight),
              unit: "PIXELS",
            }
          : undefined,
        letterSpacing:
          options.includeLetterSpacing && item.letterSpacing !== 0
            ? {
                value: item.letterSpacing * 100,
                unit: "PERCENT",
              }
            : undefined,
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      })),
    },
    null,
    2,
  );
}

function buildCliConfigExport(typeScale, settings) {
  return JSON.stringify(
    {
      version: "1.0.0",
      name: "typography-scale",
      description: "Generated typography scale configuration",
      settings: {
        baseFontSize: settings.baseFontSize,
        scaleRatio: settings.scaleRatio,
        fontFamily: settings.fontFamily,
        roundValues: settings.roundValues,
        fluidTypography: settings.fluidTypography,
        ...(settings.fluidTypography
          ? {
              fluidSettings: {
                minViewport: settings.minViewport,
                maxViewport: settings.maxViewport,
                fluidVariation: settings.fluidVariation,
                fluidScaleStrategy: settings.fluidScaleStrategy,
              },
            }
          : {}),
      },
      scale: typeScale.map((item) => ({
        id: item.id,
        label: item.label,
        semanticName: item.semanticName,
        fontSize: item.fontSize,
        fontWeight: getWeight(item),
        lineHeight: item.lineHeight,
        letterSpacing: item.letterSpacing,
        ...(item.clampValue ? { clampValue: item.clampValue } : {}),
      })),
      exports: {
        css: true,
        scss: true,
        json: true,
        ios: true,
        android: true,
        flutter: true,
        reactNative: true,
        designTokens: true,
        figma: true,
      },
    },
    null,
    2,
  );
}

function platformTokenName(item, options) {
  const value =
    options.useSemanticNames && item.semanticName ? item.semanticName : item.id;
  return camel(value);
}

function camel(value) {
  return value
    .replace(/[-_\s]+(.)?/g, (_, char = "") => char.toUpperCase())
    .replace(/^(.)/, (char) => char.toLowerCase());
}

function iosWeight(weight) {
  if (weight <= 200) return "ultraLight";
  if (weight <= 300) return "light";
  if (weight <= 400) return "regular";
  if (weight <= 500) return "medium";
  if (weight <= 600) return "semibold";
  if (weight <= 700) return "bold";
  if (weight <= 800) return "heavy";
  return "black";
}

function androidWeight(weight) {
  if (weight <= 200) return "ExtraLight";
  if (weight <= 300) return "Light";
  if (weight <= 400) return "Normal";
  if (weight <= 500) return "Medium";
  if (weight <= 600) return "SemiBold";
  if (weight <= 700) return "Bold";
  if (weight <= 800) return "ExtraBold";
  return "Black";
}

function flutterWeight(weight) {
  if (weight <= 200) return "w200";
  if (weight <= 300) return "w300";
  if (weight <= 400) return "w400";
  if (weight <= 500) return "w500";
  if (weight <= 600) return "w600";
  if (weight <= 700) return "w700";
  if (weight <= 800) return "w800";
  return "w900";
}

function reactNativeWeight(weight) {
  if (weight <= 200) return "200";
  if (weight <= 300) return "300";
  if (weight <= 400) return "normal";
  if (weight <= 500) return "500";
  if (weight <= 600) return "600";
  if (weight <= 700) return "bold";
  if (weight <= 800) return "800";
  return "900";
}
